name: Backend Test

on:
  push:
    branches: [development, master]
  pull_request:

jobs:
  test:
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
      - working-directory: eWiLL_backend
        run: docker-compose up -d

      
