name: Backend Test

on:
  push:
    branches: [development, master, v*.x]
     tags:
      - v**
  pull_request:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
      - working-directory: eWiLL_backend
        run: docker-compose up -d

      
